variable "name"              { }
variable "region"            { }
variable "vpc_cidr"          { }
variable "azs"               { }
variable "private_subnets"   { }
variable "ephemeral_subnets" { }
variable "public_subnets"    { }
variable "environment"       { }
variable "project"           { }
